"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "tr"

type Translations = {
    [key in Language]: {
        [key: string]: string
    }
}

const translations: Translations = {
    en: {
        // Navigation
        dashboard: "Dashboard",
        mockInterview: "Mock Interview",
        quizzes: "Quizzes",
        cvStudio: "CV Studio",
        schedule: "Schedule",
        analytics: "Analytics",
        profile: "Profile",
        settings: "Settings",
        logout: "Log out",
        search: "Search",
        notifications: "Notifications",
        help: "Help",
        welcome: "Welcome",
        language: "Language",
        interviewHistory: "Interview History",

        // Workspaces
        workspaces: "Workspaces",
        createWorkspace: "Create Workspace",
        createWorkspaceDesc: "Give your new workspace a name to get started.",
        renameWorkspace: "Rename Workspace",
        renameWorkspaceDesc: "Enter a new name for this workspace.",
        deleteWorkspace: "Delete Workspace",
        deleteWorkspaceDesc: "This action cannot be undone. Are you sure you want to delete",
        /** Use {{name}} placeholder; replaces deleteWorkspaceDesc + name + ? in UI */
        deleteWorkspaceMessage:
            'This action cannot be undone. Are you sure you want to delete "{{name}}"?',
        workspaceNamePlaceholder: "e.g. Frontend Role, Google Prep...",
        currentWorkspace: "Current workspace",
        cancel: "Cancel",
        create: "Create",
        delete: "Delete",
        Save: "Save",

        // Onboarding - Workspace step
        onboardingWorkspaceTitle: "Create your first workspace",
        onboardingWorkspaceDesc: "Set up a workspace for this job application. You can create more later.",
        workspaceName: "Workspace name",
        jobName: "Job title / role",
        jobNamePlaceholder: "e.g. Software Engineer at Google",
        jobDescription: "Job description",
        jobDescriptionPlaceholder: "Paste the job description or key requirements here...",
        pickEmoji: "Pick an icon",
        createAndContinue: "Create workspace & continue",
        newWorkspacePageTitle: "New workspace",
        newWorkspacePageDesc: "Add a workspace for another role or application. Same steps as your first workspace.",
        editWorkspaceTitle: "Edit workspace",
        editWorkspaceDesc: "Update name, job details, and icon. Changes are saved in this browser until a backend is connected.",
        workspaceBack: "Back",
        workspaceNotFound: "Workspace not found.",
        defaultWorkspaceName: "My workspace",
        loading: "Loading…",
        goToDashboard: "Go to Dashboard",
        onboardingStepProgress: "Step {{step}} of {{total}}",
        "Your Profile": "Your Profile",

        // Dashboard
        "Good evening": "Good evening",
        "Here's your progress overview": "Here's your progress overview",
        "Mock Interviews": "Mock Interviews",
        "Completed": "Completed",
        "Avg HR Score": "Avg HR Score",
        "Avg Technical Score": "Avg Technical Score",
        "Last 5 interviews": "Last 5 interviews",
        "CV Readiness": "CV Readiness",
        "ATS optimized": "ATS optimized",
        "Recommended Next Actions": "Recommended Next Actions",
        "Continue your preparation journey": "Continue your preparation journey",
        "Practice Behavioral Questions": "Practice Behavioral Questions",
        "You scored 75% on communication last time. Let's improve it!": "You scored 75% on communication last time. Let's improve it!",
        "Start Interview": "Start Interview",
        "Complete Algorithms Quiz": "Complete Algorithms Quiz",
        "Test your data structures knowledge with 15 questions": "Test your data structures knowledge with 15 questions",
        "Take Quiz": "Take Quiz",
        "Update Your CV": "Update Your CV",
        "Add your latest project to boost your CV score": "Add your latest project to boost your CV score",
        "Edit CV": "Edit CV",
        "Recent Activity": "Recent Activity",
        "Your latest actions and milestones": "Your latest actions and milestones",
        "This Week": "This Week",
        "Interviews": "Interviews",
        "Practice Time": "Practice Time",
        "Goal: 5 per week": "Goal: 5 per week",
        "Goal achieved!": "Goal achieved!",
        "per week": "per week",
        "Practice": "Practice",
        "Let's improve it!": "Let's improve it!",
        "Edit Goals": "Edit Goals",
        "Weekly Targets": "Weekly Targets",
        "Target": "Target",
        "Goal": "Goal",
        "H": "h",
        "Min": "min",
        "Save Goals": "Save Goals",
        "Updating...": "Updating...",
        "Goals updated successfully!": "Goals updated successfully!",
        "You're on track. Keep going!": "You're on track. Keep going!",
        "No recent activity yet.": "No recent activity yet.",
        "No skill scores yet.": "No skill scores yet.",
        "Welcome to RecruitAssistant, {{name}}!": "Welcome to RecruitAssistant, {{name}}!",
        "Let's set up your profile and your first workspace.": "Let's set up your profile and your first workspace.",
        "1. Education": "1. Education",
        "2. Workspace": "2. Workspace",
        "Where did you study?": "Where did you study?",
        "We use this to personalize your interview experience.": "We use this to personalize your interview experience.",
        "University": "University",
        "Graduation Year": "Graduation Year",
        "Configure your workspace": "Configure your workspace",
        "What job are you preparing for right now?": "What job are you preparing for right now?",
        "Saving...": "Saving...",
        "Creating...": "Creating...",
        "Finalize and Explore": "Finalize and Explore",
        "Please fill in all education details": "Please fill in all education details",
        "Please enter a workspace name": "Please enter a workspace name",
        "Failed to update profile": "Failed to update profile",
        "Failed to create workspace": "Failed to create workspace",
        "New": "New",
        "Take a baseline quiz": "Take a baseline quiz",
        "Start with a quick skill check so your dashboard can personalize the next steps.": "Start with a quick skill check so your dashboard can personalize the next steps.",
        "Set up your CV": "Set up your CV",
        "Upload or build your CV to unlock readiness tracking.": "Upload or build your CV to unlock readiness tracking.",
        "Schedule your first interview": "Schedule your first interview",
        "Add a mock interview to your weekly plan and build momentum.": "Add a mock interview to your weekly plan and build momentum.",
        "Open Schedule": "Open Schedule",
        "Your journey starts here": "Your journey starts here",
        "Complete a mock interview to start building your activity timeline.": "Complete a mock interview to start building your activity timeline.",
        "Go to Mock Interviews": "Go to Mock Interviews",
        "Discover your focus areas": "Discover your focus areas",
        "Take a baseline quiz so we can surface the skills that need attention.": "Take a baseline quiz so we can surface the skills that need attention.",
        "Skills to Focus On": "Skills to Focus On",
        "Based on your recent performance": "Based on your recent performance",
        "Upcoming": "Upcoming",
        "View All": "View All",
        "No upcoming events scheduled.": "No upcoming events scheduled.",
        "You have an interview scheduled for today. Best of luck!": "You have an interview scheduled for today. Best of luck!",
        "Don't forget your scheduled practice session today.": "Don't forget your scheduled practice session today.",
        "Improve": "Improve",
        "Your current score is": "Your current score is",
        "Targeting 80%+ will boost your readiness.": "Targeting 80%+ will boost your readiness.",
        "Weekly Quiz Goal": "Weekly Quiz Goal",
        "You've completed": "You've completed",
        "Complete one more to stay on track!": "Complete one more to stay on track!",
        "Weekly Interview Goal": "Weekly Interview Goal",
        "interviews": "interviews",
        "Keep the momentum going!": "Keep the momentum going!",
        "Optimize Your CV": "Optimize Your CV",
        "Your CV score is": "Your CV score is",
        "Improving it can significantly increase your response rate.": "Improving it can significantly increase your response rate.",
        "Explore New Topics": "Explore New Topics",
        "Try a mock interview or a new quiz to discover your strengths.": "Try a mock interview or a new quiz to discover your strengths.",
        "Go to Quizzes": "Go to Quizzes",
        "Scored": "Scored",
        "correct": "correct",
        "Completed Technical Mock Interview": "Completed Technical Mock Interview",
        "Completed HR Mock Interview": "Completed HR Mock Interview",
        "Completed practice session": "Completed practice session",
        "Updated CV": "Updated CV",
        "CV changes saved": "CV changes saved",

        // Quizzes
        "Test your technical knowledge and validate your skills": "Test your technical knowledge and validate your skills",
        "Test your knowledge and track your improvement": "Test your knowledge and track your improvement",
        "Recommended for You": "Recommended for You",
        "Start Quiz": "Start Quiz",
        "questions": "questions",
        "Your score": "Your score",
        "Retake Quiz": "Retake Quiz",
        "Exit Quiz": "Exit Quiz",
        "Quiz Complete!": "Quiz Complete!",
        "Answer Review": "Answer Review",
        "See which questions you got right and wrong": "See which questions you got right and wrong",
        "Your answer:": "Your answer:",
        "Correct answer:": "Correct answer:",
        "Back to Quizzes": "Back to Quizzes",
        "Retry Quiz": "Retry Quiz",
        "All": "All",
        "Easy": "Easy",
        "Medium": "Medium",
        "Hard": "Hard",
        "Smart Quiz Discovery": "Smart Quiz Discovery",
        "Generating Smart Quizzes...": "Generating Smart Quizzes...",
        "Analyze JD, extracting skills, and creating questions just for you.": "Analyze JD, extracting skills, and creating questions just for you.",
        "Sit tight, we're fetching your personalized quizzes.": "Sit tight, we're fetching your personalized quizzes.",
        "Try discovery to create new ones based on your Job Description.": "Try discovery to create new ones based on your Job Description.",
        "We analyzed the Job Description. Pick the skills you want to test.": "We analyzed the Job Description. Pick the skills you want to test.",
        "Analyzing Job Description...": "Analyzing Job Description...",
        "Customize Difficulty": "Customize Difficulty",
        "Generating Your personalized Quizzes...": "Generating Your personalized Quizzes...",
        "Generate Quizzes for": "Generate Quizzes for",
        "Select Skills": "Skills",
        "Quiz Language": "Quiz Language",
        "Select Skills (Max 5)": "Select Skills (Max 5)",
        "Attempts": "Attempts",
        "Attempted": "Attempted",
        "Best Score": "Best Score",
        "Filter": "Filter",
        "No quizzes found": "No quizzes found",
        "Start Discovery": "Start Discovery",
        "Technical": "Technical",

        // Mock Interview
        "Practice your interview skills with AI-powered feedback": "Practice your interview skills with AI-powered feedback",
        "Interview Setup": "Interview Setup",
        "Configure your practice session": "Configure your practice session",
        "Interview Type": "Interview Type",
        "Difficulty Level": "Difficulty Level",
        "Language": "Language",
        "Microphone": "Microphone",
        "Enable voice responses": "Enable voice responses",
        "Question Time Limit": "Question Time Limit",
        "2 minutes per question": "2 minutes per question",
        "Interview Session": "Interview Session",
        "Type your answer here...": "Type your answer here...",
        "Live Feedback": "Live Feedback",
        "Notes": "Notes",
        "Take notes during the interview...": "Take notes during the interview...",
        "Overall Score": "Overall Score",
        "Performance Overview": "Performance Overview",
        "Question-by-Question Breakdown": "Question-by-Question Breakdown",
        "Start Another Interview": "Start Another Interview",
        "Practice Weak Topics": "Practice Weak Topics",

        // Interview History
        "Interview History": "Interview History",
        "View your past interview sessions and results": "View your past interview sessions and results",
        "No interviews yet": "No interviews yet",
        "Start your first mock interview to see your history here.": "Start your first mock interview to see your history here.",
        "Go to Mock Interview": "Go to Mock Interview",
        "Text": "Text",
        "Voice": "Voice",
        "HR": "HR",
        "In Progress": "In Progress",
        "Cancelled": "Cancelled",
        "N/A": "N/A",
        "View Details": "View Details",
        "Back to History": "Back to History",
        "Interview Details": "Interview Details",
        "Questions & Answers": "Questions & Answers",
        "Your Answer": "Your Answer",
        "AI Feedback": "AI Feedback",
        "No answer provided": "No answer provided",
        "Conversation Transcript": "Conversation Transcript",
        "Full conversation from the voice interview": "Full conversation from the voice interview",
        "Interview Already Completed": "Interview Already Completed",
        "This interview has already been completed and evaluated.": "This interview has already been completed and evaluated.",
        "View Results": "View Results",
        "Start New Interview": "Start New Interview",
        "Retake Interview": "Retake Interview",

        // CV Studio
        "Build and optimize your resume with AI assistance": "Build and optimize your resume with AI assistance",
        "Personal Information": "Personal Information",
        "Full Name": "Full Name",
        "Email": "Email",
        "Phone": "Phone",
        "Location": "Location",
        "Professional Summary": "Professional Summary",
        "Education": "Education",
        "Degree": "Degree",
        "School": "School",
        "GPA": "GPA",
        "Start Date": "Start Date",
        "End Date": "End Date",
        "Experience": "Experience",
        "Role": "Role",
        "Company": "Company",
        "Responsibilities & Achievements": "Responsibilities & Achievements",
        "Projects": "Projects",
        "Project Title": "Project Title",
        "Tech Stack": "Tech Stack",
        "Description": "Description",
        "Skills": "Skills",
        "Add skill": "Add skill",
        "Target Job Description": "Target Job Description",
        "Paste the full job description here...": "Paste the full job description here...",
        "Generate CV Draft": "Generate CV Draft",
        "Generating with AI...": "Generating with AI...",
        "CV Analysis": "CV Analysis",
        "ATS Score": "ATS Score",
        "Role Match": "Role Match",
        "Missing Skills": "Missing Skills",
        "Live Preview": "Live Preview",
        "Download PDF": "Download PDF",
        "Download .tex": "Download .tex",
        "CV language": "CV language",
        "Select language": "Select language",
        "Generate CV": "Generate CV",
        "Generating CV...": "Generating CV...",
        "Generate Cover Letter": "Generate Cover Letter",
        "Generating Letter...": "Generating Letter...",
        "Failed to generate CV": "Failed to generate CV",
        "Failed to generate Cover Letter": "Failed to generate Cover Letter",
        "An error occurred while generating the CV": "An error occurred while generating the CV",
        "An error occurred while generating the Cover Letter": "An error occurred while generating the Cover Letter",
        "Excellent! AI-optimized for ATS systems": "Excellent! AI-optimized for ATS systems",
        "Good! Your CV is well-formatted for ATS systems": "Good! Your CV is well-formatted for ATS systems",
        "Optimized for your target role": "Optimized for your target role",
        "Great alignment with the target role": "Great alignment with the target role",
        "Consider adding these skills if you have experience": "Consider adding these skills if you have experience",
        "Generated Documents": "Generated Documents",
        "Fill out the form and generate your personalized CV or Cover Letter.": "Fill out the form and generate your personalized CV or Cover Letter.",
        "CV": "CV",
        "Cover Letter": "Cover Letter",
        "PDF View": "PDF View",
        "LaTeX Source": "LaTeX Source",
        "Compiling PDF...": "Compiling PDF...",
        "Compilation Failed": "Compilation Failed",
        "The backend could not render the LaTeX into a PDF. Please check the LaTeX Source tab, correct any syntax errors, and re-compile.": "The backend could not render the LaTeX into a PDF. Please check the LaTeX Source tab, correct any syntax errors, and re-compile.",
        "Download CV PDF": "Download CV PDF",
        "Download Cover Letter PDF": "Download Cover Letter PDF",
        "Re-compile PDF": "Re-compile PDF",
        "Copy LaTeX Code": "Copy LaTeX Code",
        "✨ AI Generated!": "✨ AI Generated!",
        "Your CV has been optimized for the target role. Click \"Download PDF\" to get your professional resume ready for applications.": "Your CV has been optimized for the target role. Click \"Download PDF\" to get your professional resume ready for applications.",
        "Pro Tip:": "Pro Tip:",
        "Use action verbs and quantify your achievements. For example: \"Increased user engagement by 40%\" instead of \"Improved user engagement.\"": "Use action verbs and quantify your achievements. For example: \"Increased user engagement by 40%\" instead of \"Improved user engagement.\"",
        "Upload Resume": "Upload Resume",
        "Upload your existing CV (PDF/DOCX) to autofill the form with AI assistance": "Upload your existing CV (PDF/DOCX) to autofill the form with AI assistance",
        "Parsing...": "Parsing...",
        "Special Instructions (Optional)": "Special Instructions (Optional)",
        "e.g., 'Make it more professional', 'Focus on my leadership skills', 'Keep it under one page'": "e.g., 'Make it more professional', 'Focus on my leadership skills', 'Keep it under one page'",

        // Schedule
        "Weekly Schedule": "Weekly Schedule",
        "Plan your tailored preparation journey": "Plan your tailored preparation journey",
        "View History": "View History",
        "Past Weeks Summary": "Past Weeks Summary",
        "Add Event": "Add Event",
        "Activity Title": "Activity Title",
        "Type": "Type",
        "Time": "Time",
        "Start Time": "Start Time",
        "End Time": "End Time",
        "Schedule Event": "Schedule Event",
        "Scheduling": "Scheduling",
        "Activity title is required": "Activity title is required",
        "End time must be after start time": "End time must be after start time",
        "Failed to schedule event": "Failed to schedule event",
        "No history yet.": "No history yet.",
        "Practice Session": "Practice Session",
        "Other": "Other",

        // Dashboard Activity items (Static for demo)
        "Scored 85% on behavioral questions": "Scored 85% on behavioral questions",
        "Updated CV - Added Experience": "Updated CV - Added Experience",
        "Added Software Engineering Intern at TechCorp": "Added Software Engineering Intern at TechCorp",
        "Passed System Design Quiz": "Passed System Design Quiz",
        "8/10 correct - Great improvement!": "8/10 correct - Great improvement!",
        "Started Technical Interview Practice": "Started Technical Interview Practice",
        "Completed coding challenges on arrays": "Completed coding challenges on arrays",
        "Created Your Profile": "Created Your Profile",
        "Welcome to RecruitAssistant!": "Welcome to RecruitAssistant!",

        // Mock Interview Results
        "Interview Complete!": "Interview Complete!",
        "Here's how you performed in your session": "Here's how you performed in your session",
        "Your strengths and areas for improvement": "Your strengths and areas for improvement",
        "Radar Chart Visualization": "Radar Chart Visualization",
        "Detailed feedback for each question": "Detailed feedback for each question",
        "Great job! You've improved from your last interview.": "Great job! You've improved from your last interview.",
        "Communication": "Communication",
        "Clarity": "Clarity",
        "Structure (STAR)": "Structure (STAR)",
        "Confidence": "Confidence",
        "Tip": "Tip",
        "Eye Contact": "Eye Contact",
        "Try to structure your answer using the STAR method (Situation, Task, Action, Result).": "Try to structure your answer using the STAR method (Situation, Task, Action, Result).",
        "Good eye contact maintained. keep it up!": "Good eye contact maintained. keep it up!",

        "Help": "Help",

        // Time
        "2 hours ago": "2 hours ago",
        "1 day ago": "1 day ago",
        "2 days ago": "2 days ago",
        "3 days ago": "3 days ago",
        "1 week ago": "1 week ago",

        // Quiz Categories
        "Algorithms": "Algorithms",
        "Data Structures": "Data Structures",
        "Databases": "Databases",
        "OOP": "OOP",
        "System Design": "System Design",
        "Behavioral": "Behavioral",

        // Quiz Result Feedback
        "Great job! Your answer demonstrates a solid understanding.": "Great job! Your answer demonstrates a solid understanding.",
        "Review this concept to improve your understanding.": "Review this concept to improve your understanding.",
        "Previous": "Previous",
        "Next": "Next",
        "Finish": "Finish",
        "Add": "Add",

        // Analytics
        "Track your progress and performance insights": "Track your progress and performance insights",
        "Export Report": "Export Report",
        "Quiz Score Trend": "Quiz Score Trend",
        "Comparison of your scores vs class average": "Comparison of your scores vs class average",
        "Average": "Average",
        "Interview Skill Radar": "Interview Skill Radar",
        "Holistic view of your technical and soft skills": "Holistic view of your technical and soft skills",
        "Skill Growth (Frontend vs Backend)": "Skill Growth (Frontend vs Backend)",
        "Progress over the last 4 months": "Progress over the last 4 months",
        "CV Version History": "CV Version History",
        "Track improvements to your resume": "Track improvements to your resume",
        "Current": "Current",
        "View Version": "View Version",
        "Upcoming Tasks": "Upcoming Tasks",
        "Auto-generated action items based on your performance": "Auto-generated action items based on your performance",
        "Due": "Due",
        "Strong Progress": "Strong Progress",
        "You've improved your average score by 15% over the last month. Keep up the consistent practice!": "You've improved your average score by 15% over the last month. Keep up the consistent practice!",
        "Area to Focus": "Area to Focus",
        "Your behavioral interview scores have plateaued. Consider practicing more STAR method responses.": "Your behavioral interview scores have plateaued. Consider practicing more STAR method responses.",
        "My Skills": "My Skills",
        "Problem Solving": "Problem Solving",
        "Coding": "Coding",
        "Behavioral Answers": "Behavioral Answers",
        "Code Optimization": "Code Optimization",
        "Mock Interview with HR": "Mock Interview with HR",
        "React Quiz": "React Quiz",
        "Quizzes": "Quizzes",
        "CV Builder": "CV Builder",
        "Skill Quizzes": "Skill Quizzes",
        "Progress Analytics": "Progress Analytics",

        // Landing Page
        "Your AI-powered interview companion": "Your AI-powered interview companion",
        "Practice HR and technical interviews, improve your CV, and track your progress with personalized AI feedback.": "Practice HR and technical interviews, improve your CV, and track your progress with personalized AI feedback.",
        "Start mock interview": "Start mock interview",
        "Build my CV": "Build my CV",
        "I recently graduated with a degree in Computer Science...": "I recently graduated with a degree in Computer Science...",
        "Practice with AI-powered HR and technical interviews": "Practice with AI-powered HR and technical interviews",
        "Create ATS-optimized resumes tailored to your role": "Create ATS-optimized resumes tailored to your role",
        "Test your knowledge with targeted quiz questions": "Test your knowledge with targeted quiz questions",
        "Track your improvement over time with insights": "Track your improvement over time with insights",

        "Object-Oriented Programming": "Object-Oriented Programming",
        "SQL Query Optimization": "SQL Query Optimization",
        "Behavioral Questions": "Behavioral Questions",
        "Array Algorithms Basics": "Array Algorithms Basics",
        "System Design Fundamentals": "System Design Fundamentals",
        "Advanced Data Structures": "Advanced Data Structures",
        "min": "min",
        "e.g., Python Data Structures": "e.g., Python Data Structures",

        "Software Engineer": "Software Engineer",
        "Tech Company Inc.": "Tech Company Inc.",
        "E-commerce Platform": "E-commerce Platform",
        "Built a full-stack application that...": "Built a full-stack application that...",

        "Complete Behavioral Quiz": "Complete Behavioral Quiz",
        "Practice System Design Interview": "Practice System Design Interview",
        "Update CV with new project": "Update CV with new project",
        "Review weak topics": "Review weak topics",
        "Today": "Today",
        "Tomorrow": "Tomorrow",
        "This week": "This week",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "Nov 24 - 30": "Nov 24 - 30",
        "Dec 1 - 7": "Dec 1 - 7",
        "Dec 8 - 14": "Dec 8 - 14",
        "Intrv.": "Intrv.",
        "Mock Interview": "Mock Interview",
        "Analytics": "Analytics",
        "Dec 20, 2024": "Dec 20, 2024",
        "Dec 15, 2024": "Dec 15, 2024",
        "Dec 10, 2024": "Dec 10, 2024",

        // Chart & Data Labels
        "Frontend": "Frontend",
        "Backend": "Backend",
        "archived": "Archived",
        "current": "Current",

        // Interview Questions (For Mock Interview Page)
        "Tell me about yourself and your background.": "Tell me about yourself and your background.",
        "Why are you interested in this role?": "Why are you interested in this role?",
        "Describe a challenging project you've worked on.": "Describe a challenging project you've worked on.",
        "Introduction": "Introduction",
        "Motivation": "Motivation",
        "Intern": "Intern",
        "Junior / New Grad": "Junior / New Grad",
        "Mid-Level": "Mid-Level",
        "HR / Behavioral": "HR / Behavioral",
        "English": "English",
        "Turkish": "Turkish",
        "Clear and concise introduction. Good structure.": "Clear and concise introduction. Good structure.",
        "Strong passion shown. Could elaborate more on specific aspects of the role.": "Strong passion shown. Could elaborate more on specific aspects of the role.",
        "Excellent use of STAR method. Great technical detail.": "Excellent use of STAR method. Great technical detail.",

        // Auth Pages - Login
        "Welcome back": "Welcome back",
        "Sign in to your RecruitAssistant account": "Sign in to your RecruitAssistant account",
        "Password": "Password",
        "Forgot password?": "Forgot password?",
        "Signing in...": "Signing in...",
        "Sign In": "Sign In",
        "Don't have an account?": "Don't have an account?",
        "Sign up": "Sign up",

        // Auth Pages - Register
        "Create an account": "Create an account",
        "Start your journey with RecruitAssistant": "Start your journey with RecruitAssistant",
        "Confirm Password": "Confirm Password",
        "I agree to the": "I agree to the",
        "terms and conditions": "terms and conditions",
        "Creating account...": "Creating account...",
        "Create Account": "Create Account",
        "Already have an account?": "Already have an account?",
        "Sign in": "Sign in",
        "Passwords do not match": "Passwords do not match",
        "Please agree to the terms and conditions": "Please agree to the terms and conditions",

        // Auth Pages - Forgot Password
        "Enter your email and we'll send you a link to reset your password": "Enter your email and we'll send you a link to reset your password",
        "Sending...": "Sending...",
        "Send Reset Link": "Send Reset Link",
        "Back to login": "Back to login",
        "Check your email": "Check your email",
        "We've sent a password reset link to": "We've sent a password reset link to",
        "Didn't receive the email? Check your spam folder or try again.": "Didn't receive the email? Check your spam folder or try again.",
        "Try another email": "Try another email",

        // Profile Page
        "Profile": "Profile",
        "Manage your personal information and professional details": "Manage your personal information and professional details",
        "Profile Picture": "Profile Picture",
        "Update your profile photo": "Update your profile photo",
        "Change Photo": "Change Photo",
        "Basic Information": "Basic Information",
        "Update your personal details": "Update your personal details",
        "Email Address": "Email Address",
        "Phone Number": "Phone Number",
        "Professional Title": "Professional Title",
        "Address": "Address",
        "Bio": "Bio",
        "Tell us about yourself...": "Tell us about yourself...",
        "Professional Details": "Professional Details",
        "Your education and skills": "Your education and skills",
        "Cancel": "Cancel",
        "Save Changes": "Save Changes",

        // Settings Page
        "Settings": "Settings",
        "Manage your account settings and preferences": "Manage your account settings and preferences",
        "Appearance": "Appearance",
        "Customize how the app looks on your device": "Customize how the app looks on your device",
        "Theme": "Theme",
        "Light": "Light",
        "Dark": "Dark",
        "System": "System",
        "Select the theme for the dashboard": "Select the theme for the dashboard",
        "Notifications": "Notifications",
        "Configure how you receive notifications": "Configure how you receive notifications",
        "Push Notifications": "Push Notifications",
        "Receive push notifications for important updates": "Receive push notifications for important updates",
        "Email Notifications": "Email Notifications",
        "Get notified via email for weekly progress reports": "Get notified via email for weekly progress reports",
        "Interview Reminders": "Interview Reminders",
        "Remind me to practice mock interviews": "Remind me to practice mock interviews",
        "Privacy & Security": "Privacy & Security",
        "Manage your privacy and security settings": "Manage your privacy and security settings",
        "Change Password": "Change Password",
        "Update your password to keep your account secure": "Update your password to keep your account secure",
        "Data Management": "Data Management",
        "Download My Data": "Download My Data",
        "Delete Account": "Delete Account",
        // Newly added keys
        "LinkedIn URL": "LinkedIn URL",
        "GitHub/Portfolio URL": "GitHub/Portfolio URL",
        "Project Date": "Project Date",
        "Reset password": "Reset password",
        "Enter your new password below": "Enter your new password below",
        "New Password": "New Password",
        "Confirm New Password": "Confirm New Password",
        "Re-enter your password": "Re-enter your password",
        "Password must contain:": "Password must contain:",
        "One uppercase letter": "One uppercase letter",
        "One number": "One number",
        "Resetting...": "Resetting...",
        "Reset Password": "Reset Password",
        "Password must be at least 8 characters": "Password must be at least 8 characters",
        "Password reset successful!": "Password reset successful!",
        "University": "University",
        "Graduation Year": "Graduation Year",
        "Target Role": "Target Role",
        "Name:": "Name:",
        "Graduation:": "Graduation:",
        "Not provided": "Not provided",
        "Selected Skills": "Selected Skills",
        "Your Goals": "Your Goals",
        "Attempt #": "Attempt #",
        "pts": "pts",
        "Loading...": "Loading...",
        "Your account has been created successfully! You can now log in.": "Your account has been created successfully! You can now log in.",
        "CV Language": "CV Language",
    },
    tr: {
        // Navigation
        dashboard: "Panel",
        mockInterview: "Mülakat Simülasyonu",
        quizzes: "Testler",
        cvStudio: "CV Stüdyosu",
        schedule: "Takvim",
        analytics: "Analizler",
        profile: "Profil",
        settings: "Ayarlar",
        logout: "Çıkış Yap",
        search: "Ara",
        notifications: "Bildirimler",
        help: "Yardım",
        welcome: "Hoşgeldiniz",
        language: "Dil",
        interviewHistory: "Mülakat Geçmişi",

        // Workspaces
        workspaces: "Çalışma Alanları",
        createWorkspace: "Çalışma Alanı Oluştur",
        createWorkspaceDesc: "Yeni çalışma alanınıza bir isim verin.",
        renameWorkspace: "Çalışma Alanını Yeniden Adlandır",
        renameWorkspaceDesc: "Bu çalışma alanı için yeni bir isim girin.",
        deleteWorkspace: "Çalışma Alanını Sil",
        deleteWorkspaceDesc: "Bu işlem geri alınamaz. Silmek istediğinize emin misiniz:",
        deleteWorkspaceMessage:
            'Bu işlem geri alınamaz. "{{name}}" çalışma alanını silmek istediğinize emin misiniz?',
        workspaceNamePlaceholder: "ör. Frontend Pozisyonu, Google Hazırlık...",
        currentWorkspace: "Aktif çalışma alanı",
        cancel: "İptal",
        create: "Oluştur",
        delete: "Sil",

        // Onboarding - Workspace step
        onboardingWorkspaceTitle: "İlk çalışma alanını oluştur",
        onboardingWorkspaceDesc: "Bu iş başvurusu için bir çalışma alanı kurun. Daha sonra yeni alanlar ekleyebilirsiniz.",
        workspaceName: "Çalışma alanı adı",
        jobName: "İş adı / Rol",
        jobNamePlaceholder: "ör. Google'da Yazılım Mühendisi",
        jobDescription: "İş tanımı",
        jobDescriptionPlaceholder: "İş tanımını veya ana gereksinimleri yapıştırın...",
        pickEmoji: "Bir ikon seçin",
        createAndContinue: "Çalışma alanı oluştur ve devam et",
        newWorkspacePageTitle: "Yeni çalışma alanı",
        newWorkspacePageDesc: "Başka bir rol veya başvuru için çalışma alanı ekleyin. İlk alanınızla aynı adımlar.",
        editWorkspaceTitle: "Çalışma alanını düzenle",
        editWorkspaceDesc: "İsim, iş bilgileri ve ikonu güncelleyin. Sunucu bağlanana kadar değişiklikler bu tarayıcıda saklanır.",
        workspaceBack: "Geri",
        workspaceNotFound: "Çalışma alanı bulunamadı.",
        defaultWorkspaceName: "Çalışma alanım",
        loading: "Yükleniyor…",
        goToDashboard: "Panele git",
        onboardingStepProgress: "Adım {{step}} / {{total}}",
        "Your Profile": "Profiliniz",

        // Time
        "2 hours ago": "2 saat önce",
        "1 day ago": "1 gün önce",
        "2 days ago": "2 gün önce",
        "3 days ago": "3 gün önce",
        "1 week ago": "1 hafta önce",

        // Quiz Categories (UPDATED: Kept in English)
        "Algorithms": "Algorithms",
        "Data Structures": "Data Structures",
        "Databases": "Databases",
        "OOP": "OOP (Object Oriented Programming)",
        "System Design": "System Design",
        "Behavioral": "Davranışsal", // This is a soft skill, so Turkish is fine

        // Dashboard
        "Good evening": "İyi akşamlar",
        "Here's your progress overview": "İlerleme durumuna genel bakış",
        "Mock Interviews": "Mülakatlar",
        "Completed": "Tamamlandı",
        "Avg HR Score": "Ort. İK Puanı",
        "Avg Technical Score": "Ort. Teknik Puan",
        "Last 5 interviews": "Son 5 mülakat",
        "CV Readiness": "CV Hazırlığı",
        "ATS optimized": "ATS uyumlu",
        "Recommended Next Actions": "Önerilen Sonraki Adımlar",
        "Continue your preparation journey": "Hazırlık yolculuğuna devam et",
        "Practice Behavioral Questions": "Davranışsal Sorular Çalış",
        "You scored 75% on communication last time. Let's improve it!": "Geçen sefer iletişimde %75 aldın. Geliştirelim!",
        "Start Interview": "Mülakata Başla",
        "Complete Algorithms Quiz": "Algorithms Testini Tamamla", // Mixed to allow flow but keep term English
        "Test your data structures knowledge with 15 questions": "15 soru ile Data Structures bilgini test et",
        "Take Quiz": "Teste Başla",
        "Update Your CV": "CV'ni Güncelle",
        "Add your latest project to boost your CV score": "CV puanını artırmak için son projeni ekle",
        "Edit CV": "CV Düzenle",
        "Recent Activity": "Son Aktiviteler",
        "Your latest actions and milestones": "Son işlemlerin ve dönüm noktaların",
        "This Week": "Bu Hafta",
        "Interviews": "Mülakatlar",
        "Practice Time": "Pratik Süresi",
        "Goal: 5 per week": "Hedef: Haftada 5",
        "Goal achieved!": "Hedefe ulaşıldı!",
        "per week": "haftalık",
        "Practice": "Pratik",
        "Let's improve it!": "Geliştirelim!",
        "Edit Goals": "Hedefleri Düzenle",
        "Weekly Targets": "Haftalık Hedefler",
        "Target": "Hedef",
        "Goal": "Hedef",
        "H": "s",
        "Min": "dk",
        "Save Goals": "Hedefleri Kaydet",
        "Updating...": "Güncelleniyor...",
        "Goals updated successfully!": "Hedefler başarıyla güncellendi!",
        "You're on track. Keep going!": "Yolundasın. Devam et!",
        "No recent activity yet.": "Henüz son aktivite yok.",
        "No skill scores yet.": "Henüz beceri puanı yok.",
        "Welcome to RecruitAssistant, {{name}}!": "RecruitAssistant'a Hoş Geldin, {{name}}!",
        "Let's set up your profile and your first workspace.": "Profilini ve ilk çalışma alanını oluşturalım.",
        "1. Education": "1. Eğitim",
        "2. Workspace": "2. Çalışma Alanı",
        "Where did you study?": "Nerede okudun?",
        "We use this to personalize your interview experience.": "Bunu mülakat deneyimini kişiselleştirmek için kullanıyoruz.",
        "University": "Üniversite",
        "Graduation Year": "Mezuniyet Yılı",
        "Configure your workspace": "Çalışma alanını yapılandır",
        "What job are you preparing for right now?": "Şu an hangi işe hazırlanıyorsun?",
        "Saving...": "Kaydediliyor...",
        "Creating...": "Oluşturuluyor...",
        "Finalize and Explore": "Tamamla ve Keşfet",
        "Please fill in all education details": "Lütfen tüm eğitim bilgilerini doldur",
        "Please enter a workspace name": "Lütfen bir çalışma alanı ismi gir",
        "Failed to update profile": "Profil güncellenemedi",
        "Failed to create workspace": "Çalışma alanı oluşturulamadı",
        "New": "Yeni",
        "Take a baseline quiz": "Başlangıç testini çöz",
        "Start with a quick skill check so your dashboard can personalize the next steps.": "Panelin sonraki adımları kişiselleştirebilmesi için kısa bir beceri kontrolüyle başla.",
        "Set up your CV": "CV'ni hazırla",
        "Upload or build your CV to unlock readiness tracking.": "Hazırlık takibini açmak için CV'ni yükle veya oluştur.",
        "Schedule your first interview": "İlk mülakatını planla",
        "Add a mock interview to your weekly plan and build momentum.": "Haftalık planına bir mülakat simülasyonu ekle ve ivme kazan.",
        "Open Schedule": "Takvimi Aç",
        "Your journey starts here": "Yolculuğun burada başlıyor",
        "Complete a mock interview to start building your activity timeline.": "Aktivite zaman çizelgeni oluşturmaya başlamak için bir mülakat simülasyonu tamamla.",
        "Go to Mock Interviews": "Mülakat Simülasyonlarına Git",
        "Discover your focus areas": "Odak alanlarını keşfet",
        "Take a baseline quiz so we can surface the skills that need attention.": "Dikkat gerektiren becerileri gösterebilmemiz için başlangıç testini çöz.",
        "Skills to Focus On": "Odaklanılması Gereken Beceriler",
        "Based on your recent performance": "Son performansına dayalı",
        "Upcoming": "Yaklaşanlar",
        "View All": "Tümünü Gör",
        "No upcoming events scheduled.": "Yaklaşan etkinlik yok.",
        "You have an interview scheduled for today. Best of luck!": "Bugün bir mülakatın var. Başarılar dileriz!",
        "Don't forget your scheduled practice session today.": "Bugünkü pratik seansını unutma.",
        "Improve": "Geliştir:",
        "Your current score is": "Mevcut puanın:",
        "Targeting 80%+ will boost your readiness.": "%80 ve üzerine çıkmak hazırlık durumunu artıracaktır.",
        "Weekly Quiz Goal": "Haftalık Test Hedefi",
        "You've completed": "Tamamlanan:",
        "Complete one more to stay on track!": "Yolunda gitmek için bir tane daha tamamla!",
        "Weekly Interview Goal": "Haftalık Mülakat Hedefi",
        "interviews": "mülakat",
        "Keep the momentum going!": "İvmeyi devam ettir!",
        "Optimize Your CV": "CV'ni Optimize Et",
        "Your CV score is": "CV puanın:",
        "Improving it can significantly increase your response rate.": "Puanı artırmak işe alım oranını önemli ölçüde etkileyebilir.",
        "Explore New Topics": "Yeni Konular Keşfet",
        "Try a mock interview or a new quiz to discover your strengths.": "Güçlü yanlarını keşfetmek için yeni bir test veya mülakat dene.",
        "Go to Quizzes": "Testlere Git",
        "Scored": "Puan:",
        "correct": "doğru",
        "Completed Technical Mock Interview": "Teknik Mülakat Simülasyonu Tamamlandı",
        "Completed HR Mock Interview": "İK Mülakat Simülasyonu Tamamlandı",
        "Completed practice session": "Pratik seansı tamamlandı",
        "Updated CV": "CV Güncellendi",
        "CV changes saved": "CV değişiklikleri kaydedildi",

        // Quizzes
        "Test your technical knowledge and validate your skills": "Teknik bilginizi test edin ve yeteneklerinizi doğrulayın",
        "Test your knowledge and track your improvement": "Bilgini test et ve gelişimini takip et",
        "Recommended for You": "Önerilenler",
        "Start Quiz": "Teste Başla",
        "questions": "soru",
        "Your score": "Puanın",
        "Retake Quiz": "Testi Tekrarla",
        "Exit Quiz": "Testten Çık",
        "Quiz Complete!": "Test Tamamlandı!",
        "Answer Review": "Cevap Özeti",
        "See which questions you got right and wrong": "Doğru ve yanlışlarını gör",
        "Your answer:": "Cevabın:",
        "Correct answer:": "Doğru cevap:",
        "Back to Quizzes": "Testlere Dön",
        "Retry Quiz": "Tekrar Dene",
        "All": "Tümü",
        "Easy": "Kolay",
        "Medium": "Orta",
        "Hard": "Zor",
        "Smart Quiz Discovery": "Akıllı Quiz Keşfi",
        "Generating Smart Quizzes...": "Akıllı Quizler Oluşturuluyor...",
        "Analyze JD, extracting skills, and creating questions just for you.": "İş tanımı analiz ediliyor, yetenekler çıkarılıyor ve size özel sorular oluşturuluyor.",
        "Sit tight, we're fetching your personalized quizzes.": "Lütfen bekleyin, size özel testlerinizi getiriyoruz.",
        "Try discovery to create new ones based on your Job Description.": "İş tanımınıza göre yeni testler oluşturmak için keşfi deneyin.",
        "We analyzed the Job Description. Pick the skills you want to test.": "İş tanımını analiz ettik. Test etmek istediğiniz yetenekleri seçin.",
        "Analyzing Job Description...": "İş Tanımı Analiz Ediliyor...",
        "Customize Difficulty": "Zorluğu Özelleştir",
        "Generating Your personalized Quizzes...": "Size özel testleriniz oluşturuluyor...",
        "Generate Quizzes for": "Testleri Oluştur -",
        "Select Skills": "Yetenek",
        "Quiz Language": "Quiz Dili",
        "Select Skills (Max 5)": "Yetenekleri Seçin (Maks 5)",
        "Attempts": "Deneme",
        "Attempted": "Başlanıldı",
        "Best Score": "En İyi Puan",
        "Filter": "FİLTRELE",
        "No quizzes found": "Test bulunamadı",
        "Start Discovery": "Keşfi Başlat",
        "Technical": "Teknik",

        // Mock Interview
        "Practice your interview skills with AI-powered feedback": "Yapay zeka desteğiyle mülakat becerilerini geliştir",
        "Interview Setup": "Mülakat Kurulumu",
        "Configure your practice session": "Pratik oturumunu yapılandır",
        "Interview Type": "Mülakat Tipi",
        "Difficulty Level": "Zorluk Seviyesi",
        "Language": "Dil",
        "Microphone": "Mikrofon",
        "Enable voice responses": "Sesli yanıtları etkinleştir",
        "Question Time Limit": "Soru Süre Limiti",
        "2 minutes per question": "Soru başına 2 dakika",
        "Interview Session": "Mülakat Oturumu",
        "Type your answer here...": "Cevabını buraya yaz...",
        "Live Feedback": "Canlı Geri Bildirim",
        "Notes": "Notlar",
        "Take notes during the interview...": "Mülakat sırasında not al...",
        "Overall Score": "Genel Puan",
        "Performance Overview": "Performans Özeti",
        "Question-by-Question Breakdown": "Soru Bazlı Analiz",
        "Start Another Interview": "Başka Bir Mülakata Başla",
        "Practice Weak Topics": "Zayıf Konuları Çalış",

        // Interview History
        "Interview History": "Mülakat Geçmişi",
        "View your past interview sessions and results": "Geçmiş mülakat oturumlarınızı ve sonuçlarınızı görüntüleyin",
        "No interviews yet": "Henüz mülakat yok",
        "Start your first mock interview to see your history here.": "Geçmişinizi burada görmek için ilk mülakatınızı başlatın.",
        "Go to Mock Interview": "Mülakata Git",
        "Text": "Metin",
        "Voice": "Sesli",
        "HR": "İK",
        "In Progress": "Devam Ediyor",
        "Cancelled": "İptal Edildi",
        "N/A": "N/A",
        "View Details": "Detayları Gör",
        "Back to History": "Geçmişe Dön",
        "Interview Details": "Mülakat Detayları",
        "Questions & Answers": "Sorular ve Cevaplar",
        "Your Answer": "Cevabınız",
        "AI Feedback": "Yapay Zeka Geri Bildirimi",
        "No answer provided": "Cevap verilmedi",
        "Conversation Transcript": "Konuşma Dökümü",
        "Full conversation from the voice interview": "Sesli mülakatın tam konuşma metni",
        "Interview Already Completed": "Mülakat Zaten Tamamlandı",
        "This interview has already been completed and evaluated.": "Bu mülakat zaten tamamlanmış ve değerlendirilmiş.",
        "View Results": "Sonuçları Gör",
        "Start New Interview": "Yeni Mülakat Başlat",
        "Retake Interview": "Mülakatı Tekrarla",

        // CV Studio
        "Build and optimize your resume with AI assistance": "Yapay zeka desteğiyle CV'ni oluştur ve optimize et",
        "Personal Information": "Kişisel Bilgiler",
        "Full Name": "Ad Soyad",
        "Email": "E-posta",
        "Phone": "Telefon",
        "Location": "Konum",
        "Professional Summary": "Profesyonel Özet",
        "Education": "Eğitim",
        "Degree": "Derece / Bölüm",
        "School": "Okul",
        "GPA": "Not Ortalaması",
        "Start Date": "Başlangıç Tarihi",
        "End Date": "Bitiş Tarihi",
        "Role": "Pozisyon",
        "Company": "Şirket",
        "Responsibilities & Achievements": "Sorumluluklar ve Başarılar",
        "Projects": "Projeler",
        "Project Title": "Proje Başlığı",
        "Tech Stack": "Teknoloji Yığını",
        "Description": "Açıklama",
        "Skills": "Yetenekler",
        "Add skill": "Yetenek ekle",
        "Target Job Description": "Hedef İş Tanımı",
        "Paste the full job description here...": "İş tanımını buraya yapıştır...",
        "Generate CV Draft": "CV Taslağı Oluştur",
        "Generating with AI...": "Yapay zeka ile oluşturuluyor...",
        "Save": "Kaydet",
        "CV Analysis": "CV Analizi",
        "ATS Score": "ATS Puanı",
        "Role Match": "Rol Uyumu",
        "Missing Skills": "Eksik Yetenekler",
        "Live Preview": "Canlı Önizleme",
        "Download PDF": "PDF İndir",
        "Download .tex": ".tex İndir",
        "CV language": "CV Dili",
        "Select language": "Dil Seç",
        "Generate CV": "CV Oluştur",
        "Generating CV...": "CV Oluşturuluyor...",
        "Generate Cover Letter": "Ön Yazı Oluştur",
        "Generating Letter...": "Ön Yazı Oluşturuluyor...",
        "Failed to generate CV": "CV oluşturulamadı",
        "Failed to generate Cover Letter": "Ön Yazı oluşturulamadı",
        "An error occurred while generating the CV": "CV oluşturulurken bir hata oluştu",
        "An error occurred while generating the Cover Letter": "Ön Yazı oluşturulurken bir hata oluştu",
        "Excellent! AI-optimized for ATS systems": "Harika! Yapay zeka ile ATS için optimize edildi",
        "Good! Your CV is well-formatted for ATS systems": "İyi! CV'niz ATS sistemleri için iyi formatlanmış",
        "Optimized for your target role": "Hedef rolünüz için optimize edildi",
        "Great alignment with the target role": "Hedef rolünüzle harika uyum",
        "Consider adding these skills if you have experience": "Deneyiminiz varsa bu yetenekleri eklemeyi düşünün",
        "Generated Documents": "Oluşturulan Belgeler",
        "Fill out the form and generate your personalized CV or Cover Letter.": "Kişiselleştirilmiş CV'nizi veya Ön Yazınızı oluşturmak için formu doldurun.",
        "CV": "CV",
        "Cover Letter": "Ön Yazı",
        "PDF View": "PDF Görünümü",
        "LaTeX Source": "LaTeX Kaynağı",
        "Compiling PDF...": "PDF Derleniyor...",
        "Compilation Failed": "Derleme Başarısız",
        "The backend could not render the LaTeX into a PDF. Please check the LaTeX Source tab, correct any syntax errors, and re-compile.": "Sunucu LaTeX kodunu PDF'e dönüştüremedi. Lütfen LaTeX Kaynağı sekmesini kontrol edin, sözdizimi hatalarını düzeltin ve yeniden derleyin.",
        "Download CV PDF": "CV PDF İndir",
        "Download Cover Letter PDF": "Ön Yazı PDF İndir",
        "Re-compile PDF": "PDF'i Yeniden Derle",
        "Copy LaTeX Code": "LaTeX Kodunu Kopyala",
        "✨ AI Generated!": "✨ Yapay Zeka ile Oluşturuldu!",
        "Your CV has been optimized for the target role. Click \"Download PDF\" to get your professional resume ready for applications.": "CV'niz hedef rol için optimize edildi. Profesyonel özgeçmişinizi başvurulara hazır hale getirmek için \"PDF İndir\"e tıklayın.",
        "Pro Tip:": "Profesyonel İpucu:",
        "Use action verbs and quantify your achievements. For example: \"Increased user engagement by 40%\" instead of \"Improved user engagement.\"": "Eylem fiilleri kullanın ve başarılarınızı sayılarla ifade edin. Örneğin: \"Kullanıcı etkileşimini iyileştirdim\" yerine \"Kullanıcı etkileşimini %40 artırdım\".",
        "Upload Resume": "Özgeçmiş Yükle",
        "Upload your existing CV (PDF/DOCX) to autofill the form with AI assistance": "Formu yapay zeka desteğiyle doldurmak için mevcut CV'nizi (PDF/DOCX) yükleyin",
        "Parsing...": "Çözümleniyor...",
        "Special Instructions (Optional)": "Özel Talimatlar (Opsiyonel)",
        "e.g., 'Make it more professional', 'Focus on my leadership skills', 'Keep it under one page'": "ör. 'Daha profesyonel yap', 'Liderlik becerilerime odaklan', 'Tek sayfa tut'",

        // Schedule
        "Weekly Schedule": "Haftalık Program",
        "Plan your tailored preparation journey": "Kişiye özel hazırlık sürecini planla",
        "View History": "Geçmişi Gör",
        "Past Weeks Summary": "Geçmiş Haftaların Özeti",
        "Add Event": "Etkinlik Ekle",
        "Activity Title": "Etkinlik Başlığı",
        "Type": "Tür",
        "Time": "Saat",
        "Start Time": "Başlangıç Saati",
        "End Time": "Bitiş Saati",
        "Schedule Event": "Etkinliği Planla",
        "Scheduling": "Planlanıyor",
        "Activity title is required": "Etkinlik başlığı gerekli",
        "End time must be after start time": "Bitiş saati başlangıç saatinden sonra olmalı",
        "Failed to schedule event": "Etkinlik planlanamadı",
        "No history yet.": "Henüz geçmiş yok.",
        "Practice Session": "Pratik Oturumu",
        "Other": "Diğer",

        // Dashboard Activity items
        "Scored 85% on behavioral questions": "Davranışsal sorularda %85 puan alındı",
        "Updated CV - Added Experience": "CV Güncellendi - Deneyim Eklendi",
        "Added Software Engineering Intern at TechCorp": "TechCorp'ta Yazılım Mühendisliği Stajı eklendi",
        "Passed System Design Quiz": "System Design Testi Geçildi",
        "8/10 correct - Great improvement!": "8/10 doğru - Harika gelişme!",
        "Started Technical Interview Practice": "Teknik Mülakat Çalışması Başlatıldı",
        "Completed coding challenges on arrays": "Array'lerle ilgili kodlama soruları tamamlandı",
        "Created Your Profile": "Profil Oluşturuldu",
        "Welcome to RecruitAssistant!": "RecruitAssistant'a Hoşgeldiniz!",

        // Mock Interview Results
        "Interview Complete!": "Mülakat Tamamlandı!",
        "Here's how you performed in your session": "İşte oturum performansın",
        "Your strengths and areas for improvement": "Güçlü yönlerin ve gelişim alanların",
        "Radar Chart Visualization": "Radar Grafiği Görselleştirme",
        "Detailed feedback for each question": "Her soru için detaylı geri bildirim",
        "Great job! You've improved from your last interview.": "Harika iş! Son mülakatından bu yana giriştin.",
        "Communication": "İletişim",
        "Clarity": "Netlik",
        "Structure (STAR)": "Yapı (STAR)",
        "Confidence": "Özgüven",
        "Tip": "İpucu",
        "Eye Contact": "Göz Teması",
        "Try to structure your answer using the STAR method (Situation, Task, Action, Result).": "Cevabını STAR yöntemini (Durum, Görev, Eylem, Sonuç) kullanarak yapılandırmayı dene.",
        "Good eye contact maintained. keep it up!": "Göz teması iyi korundu. Aynen devam!",
        // Quiz Result Feedback
        "Great job! Your answer demonstrates a solid understanding.": "Harika iş! Cevabın sağlam bir anlayış gösteriyor.",
        "Review this concept to improve your understanding.": "Anlayışını geliştirmek için bu konuyu tekrar et.",
        "Previous": "Önceki",
        "Next": "Sonraki",
        "Finish": "Bitir",
        "Add": "Ekle",

        // Analytics
        "Track your progress and performance insights": "Gelişimini ve performans analizlerini takip et",
        "Export Report": "Raporu Dışa Aktar",
        "Quiz Score Trend": "Test Puan Grafiği",
        "Comparison of your scores vs class average": "Puanlarının sınıf ortalamasıyla karşılaştırması",
        "Average": "Ortalama",
        "Interview Skill Radar": "Mülakat Beceri Radarı",
        "Holistic view of your technical and soft skills": "Teknik ve sosyal becerilerine bütünsel bir bakış",
        "Skill Growth (Frontend vs Backend)": "Beceri Gelişimi (Frontend vs Backend)",
        "Progress over the last 4 months": "Son 4 aydaki ilerleme",
        "CV Version History": "CV Versiyon Geçmişi",
        "Track improvements to your resume": "CV üzerindeki geliştirmeleri takip et",
        "Current": "Mevcut",
        "View Version": "Versiyonu Gör",
        "Upcoming Tasks": "Yaklaşan Görevler",
        "Auto-generated action items based on your performance": "Performansına göre otomatik oluşturulan aksiyonlar",
        "Due": "Bitiş",
        "Strong Progress": "Güçlü İlerleme",
        "You've improved your average score by 15% over the last month. Keep up the consistent practice!": "Son ayda ortalama puanını %15 geliştirdin. İstikrarlı çalışmaya devam et!",
        "Area to Focus": "Odaklanılacak Alan",
        "Your behavioral interview scores have plateaued. Consider practicing more STAR method responses.": "Davranışsal mülakat puanların sabitlendi. STAR metoduyla daha fazla pratik yapmayı düşün.",
        "My Skills": "Becerilerim",
        "Problem Solving": "Problem Çözme",
        "Coding": "Coding",
        "Behavioral Answers": "Davranışsal Cevaplar",
        "Code Optimization": "Code Optimization",
        "Mock Interview with HR": "İK ile Mülakat Simülasyonu",
        "React Quiz": "React Quiz",
        "Quizzes": "Testler",
        "CV Builder": "CV Oluşturucu",
        "Skill Quizzes": "Yetenek Testleri",
        "Progress Analytics": "İlerleme Analizi",

        // Landing Page
        "Your AI-powered interview companion": "Yapay zeka destekli mülakat arkadaşınız",
        "Practice HR and technical interviews, improve your CV, and track your progress with personalized AI feedback.": "İK ve teknik mülakatlar yapın, CV'nizi geliştirin ve kişiselleştirilmiş yapay zeka geri bildirimleriyle gelişiminizi takip edin.",
        "Start mock interview": "Mülakata başla",
        "Build my CV": "CV'mi oluştur",
        "I recently graduated with a degree in Computer Science...": "Bilgisayar Mühendisliği bölümünden yeni mezun oldum...",
        "Practice with AI-powered HR and technical interviews": "Yapay zeka destekli İK ve teknik mülakatlarla pratik yapın",
        "Create ATS-optimized resumes tailored to your role": "Rolünüze özel ATS uyumlu özgeçmişler oluşturun",
        "Test your knowledge with targeted quiz questions": "Hedeflenen test sorularıyla bilginizi ölçün",
        "Track your improvement over time with insights": "İçgörülerle zaman içindeki gelişiminizi takip edin",

        // UPDATED: Terminology reverted to English
        "Complete Behavioral Quiz": "Davranışsal Testi Tamamla",
        "Practice System Design Interview": "System Design Mülakatı Yap",
        "Update CV with new project": "CV'ye Yeni Proje Ekle",
        "Review weak topics": "Eksik Konuları Tekrar Et",
        "Today": "Bugün",
        "Tomorrow": "Yarın",
        "This week": "Bu Hafta",
        "high": "Yüksek",
        "medium": "Orta",
        "low": "Düşük",
        "Nov 24 - 30": "24 - 30 Kas",
        "Dec 1 - 7": "1 - 7 Ara",
        "Dec 8 - 14": "8 - 14 Ara",
        "Intrv.": "Mülakat",
        "Mock Interview": "Mülakat Simülasyonu",
        "Analytics": "Analizler",
        "Dec 20, 2024": "20 Ara 2024",
        "Dec 15, 2024": "15 Ara 2024",
        "Dec 10, 2024": "10 Ara 2024",

        // Terminology Updates
        "Object-Oriented Programming": "Object-Oriented Programming",
        "SQL Query Optimization": "SQL Query Optimization",
        "Behavioral Questions": "Davranışsal Sorular",
        "Array Algorithms Basics": "Array Algorithms Basics",
        "System Design Fundamentals": "System Design Fundamentals",
        "Advanced Data Structures": "Advanced Data Structures",
        "min": "dk",
        "e.g., Python Data Structures": "örn., Python Veri Yapıları",
        "Software Engineer": "Yazılım Mühendisi",
        "Tech Company Inc.": "Teknoloji Şirketi A.Ş.",
        "E-commerce Platform": "E-ticaret Platformu",
        "Built a full-stack application that...": "Full-stack bir uygulama geliştirdim...",

        // Interview Questions
        "Intern": "Stajyer",
        "Junior / New Grad": "Yeni Mezun / Junior",
        "Mid-Level": "Orta Seviye",
        "HR / Behavioral": "İK / Davranışsal",
        "English": "İngilizce",
        "Turkish": "Türkçe",
        "Spanish": "İspanyolca",
        "French": "Fransızca",
        "German": "Almanca",
        "Listening...": "Dinleniyor...",
        "Microphone disabled": "Mikrofon kapalı",
        "this week": "bu hafta",
        "improvement": "gelişme",

        // Interview Content (Explicitly ensuring these are present)
        "Introduction": "Giriş",
        "Motivation": "Motivasyon",
        "Experience": "Deneyim",
        "Tell me about yourself and your background.": "Bize kendinizden ve geçmişinizden bahsedin.",
        "Why are you interested in this role?": "Neden bu pozisyonla ilgileniyorsunuz?",
        "Describe a challenging project you've worked on.": "Üzerinde çalıştığınız zorlu bir projeyi anlatın.",
        "Clear and concise introduction. Good structure.": "Net ve öz bir giriş. Yapısı güzel.",
        "Strong passion shown. Could elaborate more on specific aspects of the role.": "Güçlü bir tutku gösterildi. Rolün belirli yönleri hakkında daha fazla detay verilebilir.",
        "Excellent use of STAR method. Great technical detail.": "STAR yönteminin mükemmel kullanımı. Harika teknik detay.",

        // Charts
        "Frontend": "Frontend",
        "Backend": "Backend",
        "archived": "Arşivlendi",
        "current": "Mevcut",

        // Auth Pages - Login
        "Welcome back": "Tekrar hoşgeldiniz",
        "Sign in to your RecruitAssistant account": "RecruitAssistant hesabınıza giriş yapın",
        "Password": "Şifre",
        "Forgot password?": "Şifremi unuttum?",
        "Signing in...": "Giriş yapılıyor...",
        "Sign In": "Giriş Yap",
        "Don't have an account?": "Hesabınız yok mu?",
        "Sign up": "Kayıt ol",

        // Auth Pages - Register
        "Create an account": "Hesap oluştur",
        "Start your journey with RecruitAssistant": "RecruitAssistant ile yolculuğunuza başlayın",
        "Confirm Password": "Şifreyi Onayla",
        "I agree to the": "Kabul ediyorum:",
        "terms and conditions": "şartlar ve koşullar",
        "Creating account...": "Hesap oluşturuluyor...",
        "Create Account": "Hesap Oluştur",
        "Already have an account?": "Zaten hesabınız var mı?",
        "Sign in": "Giriş yap",
        "Passwords do not match": "Şifreler eşleşmiyor",
        "Please agree to the terms and conditions": "Lütfen şartları ve koşulları kabul edin",

        // Auth Pages - Forgot Password
        "Enter your email and we'll send you a link to reset your password": "E-postanızı girin, şifrenizi sıfırlamak için bir bağlantı göndereceğiz",
        "Sending...": "Gönderiliyor...",
        "Send Reset Link": "Sıfırlama Bağlantısı Gönder",
        "Back to login": "Giriş sayfasına dön",
        "Check your email": "E-postanızı kontrol edin",
        "We've sent a password reset link to": "Şifre sıfırlama bağlantısı gönderildi:",
        "Didn't receive the email? Check your spam folder or try again.": "E-posta almadınız mı? Spam klasörünü kontrol edin veya tekrar deneyin.",
        "Try another email": "Başka bir e-posta dene",

        // Profile Page
        "Profile": "Profil",
        "Manage your personal information and professional details": "Kişisel bilgilerinizi ve profesyonel detaylarınızı yönetin",
        "Profile Picture": "Profil Fotoğrafı",
        "Update your profile photo": "Profil fotoğrafınızı güncelleyin",
        "Change Photo": "Fotoğrafı Değiştir",
        "Basic Information": "Temel Bilgiler",
        "Update your personal details": "Kişisel bilgilerinizi güncelleyin",
        "Email Address": "E-posta Adresi",
        "Phone Number": "Telefon Numarası",
        "Professional Title": "Profesyonel Unvan",
        "Address": "Adres",
        "Bio": "Hakkında",
        "Tell us about yourself...": "Kendinizden bahsedin...",
        "Professional Details": "Profesyonel Detaylar",
        "Your education and skills": "Eğitiminiz ve yetenekleriniz",
        "Cancel": "İptal",
        "Save Changes": "Değişiklikleri Kaydet",

        // Settings Page
        "Settings": "Ayarlar",
        "Manage your account settings and preferences": "Hesap ayarlarınızı ve tercihlerinizi yönetin",
        "Appearance": "Görünüm",
        "Customize how the app looks on your device": "Uygulamanın cihazınızda nasıl görüneceğini özelleştirin",
        "Theme": "Tema",
        "Light": "Açık",
        "Dark": "Koyu",
        "System": "Sistem",
        "Select the theme for the dashboard": "Panel için tema seçin",
        "Notifications": "Bildirimler",
        "Configure how you receive notifications": "Bildirim tercihlerinizi yapılandırın",
        "Push Notifications": "Anlık Bildirimler",
        "Receive push notifications for important updates": "Önemli güncellemeler için anlık bildirim alın",
        "Email Notifications": "E-posta Bildirimleri",
        "Get notified via email for weekly progress reports": "Haftalık ilerleme raporları için e-posta ile bildirim alın",
        "Interview Reminders": "Mülakat Hatırlatıcıları",
        "Remind me to practice mock interviews": "Mülakat pratiği yapmamı hatırlat",
        "Privacy & Security": "Gizlilik ve Güvenlik",
        "Manage your privacy and security settings": "Gizlilik ve güvenlik ayarlarınızı yönetin",
        "Change Password": "Şifre Değiştir",
        "Update your password to keep your account secure": "Hesabınızı güvende tutmak için şifrenizi güncelleyin",
        "Data Management": "Veri Yönetimi",
        "Download My Data": "Verilerimi İndir",
        "Delete Account": "Hesabı Sil",
        // Newly added keys
        "LinkedIn URL": "LinkedIn URL",
        "GitHub/Portfolio URL": "GitHub/Portfolyo URL",
        "Project Date": "Proje Tarihi",
        "Reset password": "Şifreyi sıfırla",
        "Enter your new password below": "Yeni şifrenizi aşağıya girin",
        "New Password": "Yeni Şifre",
        "Confirm New Password": "Yeni Şifreyi Onayla",
        "Re-enter your password": "Şifrenizi tekrar girin",
        "Password must contain:": "Şifreniz şunları içermelidir:",
        "One uppercase letter": "Bir büyük harf",
        "One number": "Bir rakam",
        "Resetting...": "Sıfırlanıyor...",
        "Reset Password": "Şifreyi Sıfırla",
        "Password must be at least 8 characters": "Şifre en az 8 karakter olmalıdır",
        "Password reset successful!": "Şifre sıfırlama başarılı!",
        "University": "Üniversite",
        "Graduation Year": "Mezuniyet Yılı",
        "Target Role": "Hedef Rol",
        "Name:": "Ad:",
        "Graduation:": "Mezuniyet:",
        "Not provided": "Belirtilmedi",
        "Selected Skills": "Seçilen Yetenekler",
        "Your Goals": "Hedefleriniz",
        "Attempt #": "Deneme #",
        "pts": "puan",
        "Loading...": "Yükleniyor...",
        "Your account has been created successfully! You can now log in.": "Hesabınız başarıyla oluşturuldu! Şimdi giriş yapabilirsiniz.",
        "CV Language": "CV Dili",
    },
}

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("tr")

    useEffect(() => {
        // Basic persistence
        const savedLang = localStorage.getItem("language") as Language
        if (savedLang && (savedLang === "en" || savedLang === "tr")) {
            setLanguage(savedLang)
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        localStorage.setItem("language", lang)
    }

    const t = (key: string) => {
        return translations[language][key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
